spring:
    application:
        name: store

    datasource:
        url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
        username: root
        password:
    jpa:
        show-sql: true # show sql in the console when running application
        properties:
            jakarta:
                persistence:
                    schema-generation:
                        scripts:
                            action: none
                            create-target: src/main/resources/db/migration/V2__add-home-column-in-address-table.sql
                        create-source: metadata
                        database:

    jwt:
        secret: ${JWT_SECRET} 
